import subprocess
from pathlib import Path
from uuid import uuid4


def _escape_latex(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "$": r"\$",
        "&": r"\&",
        "#": r"\#",
        "_": r"\_",
        "%": r"\%",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in value)


def _inject_tailored_block(
    master_cv_latex: str,
    tailored_summary: str,
    tailored_experience_bullets: list[str],
    selected_projects: list[dict],
) -> str:
    summary = _escape_latex(tailored_summary)
    bullets = "\n".join(
        f"\\item {_escape_latex(item)}" for item in tailored_experience_bullets[:6]
    ) or r"\item Tailored experience details unavailable."

    project_lines = []
    for project in selected_projects[:4]:
        name = _escape_latex(str(project.get("name", "Project")))
        desc = _escape_latex(
            str(
                project.get("description")
                or project.get("readme_summary")
                or project.get("reason")
                or ""
            )
        )
        project_lines.append(f"\\item \\textbf{{{name}}} --- {desc}".strip())

    projects = "\n".join(project_lines) or r"\item No ranked projects provided."

    tailored_block = f"""
\\clearpage
\\section*{{Tailored Version}}
\\subsection*{{Professional Summary}}
{summary}

\\subsection*{{Tailored Experience Highlights}}
\\begin{{itemize}}
{bullets}
\\end{{itemize}}

\\subsection*{{Selected Projects}}
\\begin{{itemize}}
{projects}
\\end{{itemize}}
"""

    marker = r"\end{document}"
    if marker in master_cv_latex:
        return master_cv_latex.replace(marker, tailored_block + "\n" + marker)

    return master_cv_latex + "\n" + tailored_block + "\n" + marker + "\n"


def export_latex_to_pdf_with_tectonic(
    master_cv_latex: str,
    tailored_summary: str,
    tailored_experience_bullets: list[str],
    selected_projects: list[dict],
) -> str:
    if not master_cv_latex.strip():
        return ""

    output_dir = Path("/tmp/cv_tailor_exports")
    output_dir.mkdir(parents=True, exist_ok=True)

    stem = f"tailored_resume_{uuid4().hex}"
    tex_path = output_dir / f"{stem}.tex"
    pdf_path = output_dir / f"{stem}.pdf"

    latex_source = _inject_tailored_block(
        master_cv_latex=master_cv_latex,
        tailored_summary=tailored_summary,
        tailored_experience_bullets=tailored_experience_bullets,
        selected_projects=selected_projects,
    )
    tex_path.write_text(latex_source, encoding="utf-8")

    try:
        subprocess.run(
            ["tectonic", "--outdir", str(output_dir), str(tex_path)],
            check=True,
            capture_output=True,
            text=True,
            timeout=90,
        )
    except FileNotFoundError as exc:
        raise RuntimeError("tectonic is not installed in the backend container") from exc
    except subprocess.CalledProcessError as exc:
        details = (exc.stderr or exc.stdout or "").strip()
        raise RuntimeError(f"LaTeX compilation failed: {details[:800]}") from exc
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError("LaTeX compilation timed out") from exc
    finally:
        tex_path.unlink(missing_ok=True)

    if not pdf_path.exists():
        raise RuntimeError("PDF was not generated by tectonic")

    return str(pdf_path)
